version: '3.8'

services:
  db:
    image: postgres:14.2-alpine
    container_name: schedule_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: students_db
    ports:
      - 5432:5432
    volumes:
      - ./src/main/resources/database-schema.sql:/docker-entrypoint-initdb.d/database-schema.sql